// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNDTMPdEPIMhjsP1H1RfofXOkdxP9Kn0',
    appId: '1:144313333765:web:0a4d63897622028318046c',
    messagingSenderId: '144313333765',
    projectId: 'smartfootball-app-2026',
    authDomain: 'smartfootball-app-2026.firebaseapp.com',
    storageBucket: 'smartfootball-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZzYxTY0P9HY3mtNRpb8H-q5Yru0MmgU',
    appId: '1:144313333765:android:9df1e3cf6115928918046c',
    messagingSenderId: '144313333765',
    projectId: 'smartfootball-app-2026',
    storageBucket: 'smartfootball-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7N3BZH5Z6omnrvjIwpVmZ729N8fNpDyQ',
    appId: '1:144313333765:ios:4fdc93548ec19a5d18046c',
    messagingSenderId: '144313333765',
    projectId: 'smartfootball-app-2026',
    storageBucket: 'smartfootball-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartfootballPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7N3BZH5Z6omnrvjIwpVmZ729N8fNpDyQ',
    appId: '1:144313333765:ios:4fdc93548ec19a5d18046c',
    messagingSenderId: '144313333765',
    projectId: 'smartfootball-app-2026',
    storageBucket: 'smartfootball-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartfootballPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnNDTMPdEPIMhjsP1H1RfofXOkdxP9Kn0',
    appId: '1:144313333765:web:f244f0b00ac5ad8c18046c',
    messagingSenderId: '144313333765',
    projectId: 'smartfootball-app-2026',
    authDomain: 'smartfootball-app-2026.firebaseapp.com',
    storageBucket: 'smartfootball-app-2026.firebasestorage.app',
  );
}
